fix: flaky tests `Gas Fee Tokens - EIP-7702` (#33694)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**
This test is flaky, with the error:

```javascript
ElementClickInterceptedError: Element <span class="mm-box mm-icon mm-icon--size-sm mm-box--display-inline-block mm-box--color-inherit"> is not clickable at point (353,514) because another element <div class="mm-box mm-banner-base toasts-container__banner-base undefined mm-box--padding-3 mm-box--display-flex mm-box--gap-2 mm-box--background-color-background-default"> obscures it
```

The problem is that anytime we select a token for paying gas fees, a
toast appears informing about that. This toast is automatically closed
after some seconds.
If it's closed fast enough, we can proceed with the next steps, but if
it takes a bit too long, the toast obscures the other elements, and the
spec fails.

The fix is to click the close button if the toast is there, using
`clickElementSafe`. This way we mitigate race conditions around this
behaviour.



![test-failure-screenshot-3](https://github.com/user-attachments/assets/e38f0a20-8f21-4d54-9bda-c09c02cdc73c)






[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/33694?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. All tests should pass

## **Screenshots/Recordings**

See the behavior, where the toast message automatically disappears after
some seconds after selecting a token


https://github.com/user-attachments/assets/cf421abd-922a-4a1c-8040-b8078b99e798

<!-- [screenshots/recordings] -->

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.