feat: Auto-failover to Quicknode when Infura is down (#31089)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

<!--
Write a short description of the changes included in this pull request,
also include relevant motivation and context. Have in mind the following
questions:
1. What is the reason for the change?
2. What is the improvement/solution?
-->

When Infura goes down, we want to automatically and invisibly redirect
requests from Infura RPC endpoints to Quicknode endpoints.

Some context:

- There is not one central Quicknode RPC endpoint that all Infura
requests will be forwarded to; rather, each Infura-supported chain gets
its own Quicknode endpoint. All of the Infura RPC endpoints that
Quicknode currently supports are:
  - Ethereum Mainnet
  - Linea Mainnet
  - Arbitrum Mainnet
  - Avalanche
  - Optimism (OP) Mainnet
  - Polygon Mainnet
  - Base Mainnet
- These Quicknode endpoint URLs contain an API key, so to keep them
secret, we assume they are stored in environment variables.
- The failover behavior itself is already present in
`@metamask/network-controller`, where a new `failoverRpcUrls` property
has been added to the `RpcEndpoint` type.
- In a previous commit, we already upgraded
`@metamask/network-controller`, which also modified how requests are
generally made so that failed requests are automatically retried (and
retries are paused if there are too many consecutive failures).
- To save money, the Quicknode endpoints will usually stay offline. When
Infura goes down, we send a signal via Segment. By triggering a backend
service this will cause Quicknode to come online. This takes a bit of
time, so we need to account for this.
- We also want to be able to control the behavior via a feature flag.

Given this, this commit:

- Adds a migration to fill in `failoverRpcUrls` for all supported Infura
RPC endpoints in NetworkController state with Quicknode endpoints.
- Listens for when Infura is unavailable (fails too many times) and
creates a Segment event so that Quicknode can be automatically
activated.
- Configures NetworkController with a longer retry timeout for the block
tracker. While Infura is down but we are waiting for Quicknode to come
online, we don't want the failover logic to think that Quicknode is also
down. This lengthened timeout will allow us to wait longer.
- Adds some minimal UI to allow users to see that Infura endpoints have
a failover URL assigned. The failover URL field is non-editable.
- Listens for when the feature flag is turned on and off and calls
appropriate methods in NetworkController to enable or disable the
failover behavior. This also shows or hides the aforementioned UI.

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/31089?quickstart=1)

## **Related issues**

Closes https://github.com/MetaMask/metamask-extension/issues/31092.

## **Manual testing steps**

There are 7 environment variables that you need to have set in
`.metamaskrc` before you begin. Please contact me in Slack and I will
give them to you.

### Testing the UI changes

1. Check out this branch.
2. Run `yarn install`, then run `yarn webpack --watch` / `yarn start`.
3. Set up an account if necessary.
4. Open MetaMask in full-screen.
5. Open the network switcher and click on "Edit" next to "Ethereum
Mainnet".
6. Under Default RPC URL, you should see a truncated version of the
Quicknode URL below `mainnet.infura.io`.
7. Next to "Infura", you should see a "Failover" tag, and under the "RPC
URL" field, you should see a new field "Failover RPC URL" which should
contain a truncated Quicknode URL.
8. Press the back arrow.
9. Add "Avalanche Network C-Chain" (which is an Infura-supported
"additional" network).
10. Open the network switcher again, and click on "Edit" next to
"Avalanche Network C-Chain".
11. Next to "Infura", you should see a "Failover" tag, and under the
"RPC URL" field, you should see a new field "Failover RPC URL" which
should contain a truncated Quicknode URL.
12. Press the back arrow.
13. Click on "Add a custom network".
14. Add a new network, such as "Flare Mainnet":
https://chainlist.wtf/chain/14/. Type in a network name, add a new RPC
URL, then type in the chain ID and the symbol.
15. Try switching to the new network. You should not see any errors
doing so.
16. Click on the network switcher and edit Flare. You should not see a
tag next to the name of the network, and you should not see a "Failover
RPC URL" field beneath "RPC URL".
17. Go to the MetaMask docs for `wallet_addEthereumChain`:
https://docs.metamask.io/wallet/reference/json-rpc-methods/wallet_addethereumchain/
18. Connect the wallet.
19. Run the request (which should add Gnosis). (You may see a message
"setTokenNetworkFilter is not a function" but the network should still
be added.)
20. Switch to the wallet and click on the network switcher.
21. Go to edit Gnosis. You should not see a tag next to the name of the
network, and you should not see a "Failover RPC URL" field beneath "RPC
URL".

## Testing the failover logic

1. Check out this branch locally.
2. We need to lower the time that the RPC failover logic waits before
trying an unavailable endpoint. Open `metamask-controller.js` and add
the following lines:
    ``` diff
      getRpcServiceOptions: (rpcEndpointUrl) => {
        const maxRetries = 4;
        const commonOptions = {
          fetch: globalThis.fetch.bind(globalThis),
          btoa: globalThis.btoa.bind(globalThis),
        };

        if (getIsQuicknodeEndpointUrl(rpcEndpointUrl)) {
          return {
            ...commonOptions,
            policyOptions: {
              maxRetries,
// When we fail over to Quicknode, we expect it to be down at
// first while it is being automatically activated. If an endpoint
// is down, the failover logic enters a "cooldown period" of 30
// minutes. We'd really rather not enter that for Quicknode, so
              // keep retrying longer.
              maxConsecutiveFailures: (maxRetries + 1) * 14,
            },
          };
        }

        return {
          ...commonOptions,
          policyOptions: {
            maxRetries,
            // Ensure that the circuit does not break too quickly.
            maxConsecutiveFailures: (maxRetries + 1) * 7,
    +       circuitBreakDuration: 60 * SECONDS
          },
        };
      },
    ```
3. Run `yarn install`, then run `yarn webpack --watch` / `yarn start`.
4. Reload the extension if necessary.
6. Open the background or service worker in devtools. Switch to the
Network tab.
7. Open the extension in full screen mode.
8. Click on the network switcher and choose Linea.
9. In Dev Tools, see that requests to Infura succeed.
10. Log into the MetaMask Developer portal.
11. Click on "Infura RPC" in the sidebar.
12. Click on the "All Endpoints" tab if not already selected.
13. Uncheck Linea Mainnet. Click "Save Changes".
14. In Dev Tools, you should soon seeing red lines on the Network tab
that correspond to Infura requests.
15. Switch to the Console tab. You should see messages like:
    ```
Error: PollingBlockTracker - encountered an error while attempting to
update latest block:
    ```
    and:
    ```
    Could not parse response as it is not valid JSON
    ```
16. Keep waiting. After a few minutes, you should then start seeing a
message:
    ```
Creating Segment event "RPC Service Unavailable" with chain_id_caip:
"eip155:59144", rpc_endpoint_url: linea-mainnet.infura.io
    ```
17. Now switch back to the Network tab and you should start seeing
requests to a different network. Click on one of these and you should
see requests to `compatible-late-dinghy.linea-mainnet.quiknode.pro`.
19. Now switch back to the MetaMask Developer console and re-enable
Linea Mainnet.
20. Back on the Network tab in Dev Tools, wait a minute. You should
start seeing requests to Infura again instead of Quicknode.

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

### **Before**

<!-- [screenshots/recordings] -->

### **After**

This is what it looks like when viewing an Infura network:

<img width="376" alt="Screenshot 2025-05-07 at 10 13 03 PM"
src="https://github.com/user-attachments/assets/d64af05f-f593-4fb9-aad0-7b23fb7b58e1"
/>

<img width="374" alt="Screenshot 2025-05-07 at 10 13 11 PM"
src="https://github.com/user-attachments/assets/a77a2b8a-e188-4bf5-9ace-c20b96603523"
/>

This is what it looks like when viewing a non-Infura network:

<img width="380" alt="Screenshot 2025-05-07 at 10 13 26 PM"
src="https://github.com/user-attachments/assets/a9ba6ae6-3ab1-4596-a3e1-130316697b3d"
/>

Here is a screen recording showing all of the supported Infura networks
and their failover URLs:


https://github.com/user-attachments/assets/975aa597-75d5-41ea-a2ba-356f1aea66fe

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.

---------

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>
Co-authored-by: MetaMask Bot <metamaskbot@users.noreply.github.com>