fix: flaky test `Test Snap Signature Insights tests Signature Insights functionality` (#25028)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

This PR fixes the flay test `Test Snap Signature Insights tests
Signature Insights functionality`.
The problem is a race condition where, sometimes the snap signature
insights is not displayed after clicking Sign, and this causes to
directly close the MM Dialog. Then the subsequent steps cannot be
performed, even the screenshot of the error cannot be performed as it
cannot locate the window.

This problem was alreayd identified in the PR which introduced the Snap
Signature Insights
[here](https://github.com/MetaMask/metamask-extension/pull/22485#issuecomment-1933728345)
and from Frederik, this is the expect behaviour:

> For 1 I believe this is simply a timing issue, we don't currently
block the UI from proceeding while waiting for snaps to respond. We
could if that is preferable, but currently don't.

So the proposed solution here is to add a small delay before clicking
sign. The reason for that is because there is no wait condition that can
indicate us that the snap is ready.

- ci logs:

```
[driver] Called 'waitForSelector' with arguments [{"text":"0x4578616d706c652060706572736f6e616c5f7369676e60206d657373616765","tag":"p"}]
Failure on testcase: 'Test Snap Signature Insights tests Signature Insights functionality', for more information see the artifacts tab in CI

NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
```

- ci failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/85243/workflows/7d9ccbcc-c358-4a10-8cc7-e9a2b1353f37/jobs/3086510/tests

Furthermore we are also removing the extra steps for connecting to the
test dapp and enabling eth_sign, and we use fixtures.


[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/25028?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Check ci
2. Run test multiple times `yarn test:e2e:single
test/e2e/snaps/test-snap-siginsights.spec.js --browser=chrome
--leave-running --retryUntilFailure --retries=10`

## **Screenshots/Recordings**
See how if the snaps is not ready, whenever clicking Sign, the dialog
will immediately close.
You can also check the video in the PR were I reported the issue above


https://github.com/MetaMask/metamask-extension/assets/54408225/70edd8e5-a7a4-4aa7-8808-bd63b58df84e




## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.