test: mock snaps execution environments (#32950)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

In Snap tests, we often see this error:

```js
UnexpectedAlertOpenError: Unexpected alert dialog detected. Performed handler "dismiss". Dialog text: The Snaps execution environment failed to start.
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:523:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:524:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:456:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async WindowHandles.getCurrentWindowProperties (test/e2e/background-socket/window-handles.ts:71:22)
    at async WindowHandles.switchToHandleAndCheckForProperty (test/e2e/background-socket/window-handles.ts:205:28)
    at async WindowHandles.switchToWindowWithProperty (test/e2e/background-socket/window-handles.ts:161:31)
    at async Driver.switchToWindowWithTitle (test/e2e/webdriver/driver.js:1168:12)
    at async openTestSnapClickButtonAndInstall (test/e2e/page-objects/flows/install-test-snap.flow.ts:46:3)
    at async <anonymous> (test/e2e/snaps/test-snap-clientstatus.spec.ts:23:9)
    at async withFixtures (test/e2e/helpers.js:307:5)
    at async Context.<anonymous> (test/e2e/snaps/test-snap-clientstatus.spec.ts:11:5)
```

This PR adds a global mock for the execution environments (html and js)
using the local files from the existing dependency. It also removes this
entry from the allow-list of live requests.
This mitigates all the flakiness around this live request affecting snap
tests.

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/32950?quickstart=1)

## **Related issues**

Fixes: this https://github.com/MetaMask/metamask-extension/issues/32949
but also, other snap tests failing for the same error

## **Manual testing steps**

1. All tests should pass

## **Screenshots/Recordings**


![image](https://github.com/user-attachments/assets/6cab8c3e-de04-4504-8f31-ebf48442623f)


## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.