fix: revert jest collect coverage patterns (#27583)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

Reverts the coverage patterns for unit tests.
When we started to collect coverage from the types dir, we started to
get the following error from babel parser:
```
ERROR: /home/runner/work/metamask-extension/metamask-extension/types/global.d.ts: 'export declare' must be followed by an ambient declaration.
```

Removing the types dir from the coverage paths would be enough to fix
it, but it was suggested by the Platform team (@itsyoboieltr) to revert
completely the changes added on this
[PR](https://github.com/MetaMask/metamask-extension/pull/27282/files).

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/27583?quickstart=1)

## **Related issues**

Fixes: N/A


## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.

Co-authored-by: legobeat <109787230+legobeat@users.noreply.github.com>